Insert into DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATIONID) values (10,'HR1',1);
Insert into DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATIONID) values (50,'Marketing',3);
Insert into DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATIONID) values (20,'IT',1);
Insert into DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATIONID) values (30,'SALES',4);
Insert into DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATIONID) values (40,'Training',null);
