REM INSERTING into LOCATION_DTLS
Insert into LOCATION_DTLS (LOCATIONID,CITY) values (5,'HYDERABAD');
Insert into LOCATION_DTLS (LOCATIONID,CITY) values (1,'Pune');
Insert into LOCATION_DTLS (LOCATIONID,CITY) values (2,'BENGLORE');
Insert into LOCATION_DTLS (LOCATIONID,CITY) values (3,'Chennai');
Insert into LOCATION_DTLS (LOCATIONID,CITY) values (4,'GOA');
Insert into LOCATION_DTLS (LOCATIONID,CITY) values (6,'AURANGABAD');
