
  CREATE TABLE "EMPLOYEES" 
   (	"EMPLOYEEID" NUMBER(*,0) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(30 BYTE), 
	"TITLEOFCOURTESY" VARCHAR2(25 BYTE), 
	"BIRTHDATE" DATE, 
	"HIREDATE" DATE, 
	"ADDRESS" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(20 BYTE) CONSTRAINT "C1" NOT NULL ENABLE, 
	"REGION" VARCHAR2(15 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(15 BYTE), 
	"HOMEPHONE" VARCHAR2(24 BYTE), 
	"EXTENSION" VARCHAR2(4 BYTE), 
	"PHOTO" BLOB, 
	"NOTES" CLOB, 
	"REPORTSTO" NUMBER(*,0), 
	"PHOTOPATH" VARCHAR2(255 BYTE), 
	 CONSTRAINT "PK_EMPLOYEES" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_EMPLOYEES_EMPLOYEES" FOREIGN KEY ("REPORTSTO")
	  REFERENCES "EMPLOYEES" ("EMPLOYEEID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("NOTES") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;