
  CREATE TABLE "PRODUCTS" 
   (	"PRODUCTID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCTNAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SUPPLIERID" NUMBER(*,0), 
	"CATEGORYID" NUMBER(*,0), 
	"QUANTITYPERUNIT" VARCHAR2(20 BYTE), 
	"UNITPRICE" NUMBER(12,2) DEFAULT 0, 
	"UNITSINSTOCK" NUMBER(*,0) DEFAULT 0, 
	"UNITSONORDER" NUMBER(*,0) DEFAULT 0, 
	"REORDERLEVEL" NUMBER(*,0) DEFAULT 0, 
	"DISCONTINUED" NUMBER(*,0) DEFAULT 0
   , 
	 CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CHECK (UnitPrice >=0) ENABLE, 
	 CHECK (ReorderLevel >= 0) ENABLE, 
	 CHECK (UnitsInStock >= 0) ENABLE, 
	 CHECK (UnitsOnOrder >=0) ENABLE, 
	 CONSTRAINT "FK_PRODUCTS_CATEGORIES" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "CATEGORIES" ("CATEGORYID") ENABLE, 
	 CONSTRAINT "FK_PRODUCTS_SUPPLIERS" FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "SUPPLIERS" ("SUPPLIERID") DISABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;