
  CREATE TABLE "ORDERS" 
   (	"ORDERID" NUMBER(*,0) NOT NULL ENABLE, 
	"CUSTOMERID" CHAR(5 BYTE), 
	"EMPLOYEEID" NUMBER(*,0), 
	"ORDERDATE" DATE, 
	"REQUIREDDATE" DATE, 
	"SHIPPEDDATE" DATE, 
	"SHIPVIA" NUMBER(*,0), 
	"FREIGHT" NUMBER(12,2) DEFAULT 0, 
	"SHIPNAME" VARCHAR2(40 BYTE), 
	"SHIPADDRESS" VARCHAR2(60 BYTE), 
	"SHIPCITY" VARCHAR2(15 BYTE), 
	"SHIPREGION" VARCHAR2(15 BYTE), 
	"SHIPPOSTALCODE" VARCHAR2(10 BYTE), 
	"SHIPCOUNTRY" VARCHAR2(15 BYTE), 
	 CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ORDERS_CUSTOMERS" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "CUSTOMERS" ("CUSTOMERID") ENABLE, 
	 CONSTRAINT "FK_ORDERS_EMPLOYEES" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "EMPLOYEES" ("EMPLOYEEID") ENABLE, 
	 CONSTRAINT "FK_ORDERS_SHIPPERS" FOREIGN KEY ("SHIPVIA")
	  REFERENCES "SHIPPERS" ("SHIPPERID") DISABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;