
  CREATE TABLE "ORDER_DETAILS" 
   (	"ORDERID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCTID" NUMBER(*,0) NOT NULL ENABLE, 
	"UNITPRICE" NUMBER(12,2) DEFAULT 0, 
	"QUANTITY" NUMBER(*,0) DEFAULT 1, 
	"DISCOUNT" FLOAT(63) DEFAULT 0
   , 
	 CONSTRAINT "PK_ORDER_DETAILS" PRIMARY KEY ("ORDERID", "PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CHECK (Discount >= 0 and (Discount <=1)) ENABLE, 
	 CHECK (Quantity > 0) ENABLE, 
	 CHECK (UnitPrice >= 0) ENABLE, 
	 CONSTRAINT "FK_ORDER_DETAILS_ORDERS" FOREIGN KEY ("ORDERID")
	  REFERENCES "ORDERS" ("ORDERID") DISABLE, 
	 CONSTRAINT "FK_ORDER_DETAILS_PRODUCTS" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") DISABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
